version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: node123
  MYSQL_DATABASE: nodedb

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/db
    networks:
      - app-network

  nodejs:
    depends_on:
      - mysql-db
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: container_nodejs
    environment:
      <<: *common-variables      
      API_PORT: 8080
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    image: nginx:stable
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


